### ISSUE TITLE
IVPage.GetResults exception

### ISSUE THREAD

**Issue by wouterroos** [NetOfficeFw/NetOffice#18]
While trying to get the `IVPage.GetResults()` method working using [this](https://saveenr.gitbooks.io/visioautomation_docs/content/visio-and-c/getresults.html) example, I get the following exception. Am I doing anything wrong? A similar method `IVPage.SetResults()` works fine.

```
---------------------------

---------------------------
System.Runtime.InteropServices.COMException (0x80004005): See inner exception(s) for details. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Type mismatch. (Exception from HRESULT: 0x80020005 (DISP_E_TYPEMISMATCH))

   --- End of inner exception stack trace ---

   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)

   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)

   at NetOffice.Invoker.Method(COMObject comObject, String name, Object[] paramsArray, ParameterModifier[] paramModifiers)

   at NetOffice.Invoker.Method(COMObject comObject, String name, Object[] paramsArray, ParameterModifier[] paramModifiers)

   at NetOffice.VisioApi.IVPage.GetResults(Int16[] sID_SRCStream, Int16 flags, Object[] unitsNamesOrCodes, Object[]& resultArray)
---------------------------
OK   
---------------------------

```

**Comment by wouterroos** [comment]
Some additional findings: If I use the Microsoft API (`Microsoft.Office.Interop.Visio`) it works fine. I suspect that is has something to do with the fact that the `NetOffice` API uses an `object[]` as `resultArray` whereas the Microsoft API uses the plain `Array` type.

**Comment by jozefizso** [comment]
Can you provide a sample project that exhibits this issue so we can more easily determine the issue?

**Comment by jozefizso** [comment]
Feel free to reopen the issue with sample project.
