### ISSUE TITLE
DialogEditorColor Show() exception

### ISSUE THREAD

**Issue by joness95** [NetOfficeFw/NetOffice#197]
In Example06 trying to show DialogEditorColor exception is thrown

NetOffice.Exceptions.MethodCOMException
  HResult=0x80004005
  Nachricht = Failed to proceed Method on Excel.Dialog=>Show.
  Quelle = NetOffice
  Stapelüberwachung:
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.ExcelApi.Dialog.Show()
   at ExcelExamplesCS4.Example06.buttonStartExample_Click(Object sender, EventArgs e) in G:\Repositories\C#\NetOffice 1.7.4.3\.NET 4\Examples\Excel\C#\Standard Examples\ExcelExamples\Examples\Example06.cs:line 95
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at ExampleBase.AreaForm.ShowForm(IWin32Window owner, IExample example)
   at ExampleBase.ExampleForm.ExamplesView_MouseDoubleClick(Object sender, MouseEventArgs e)

Innere Ausnahme 1:
TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht.

Innere Ausnahme 2:
COMException: Die Show-Eigenschaft des Dialog-Objektes kann nicht zugeordnet werden.

**Comment by jozefizso** [comment]
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)

Inner Exception 1:
COMException: Unable to get the Show property of the Dialog class
```


![image](https://user-images.githubusercontent.com/287778/46909922-e1e90e00-cf3a-11e8-9407-0cfc2dab6f8a.png)

**Comment by jozefizso** [comment]
The **xlDialogEditColor** dialog requires a single argument - the index of a color which will be selected in the dialog.

> The **xlDialogEditColor** option does require one argument.  There are 56 color positions available in Excel; when calling the Color window it is necessary to state the which color position to be edited.
>
> https://exceloffthegrid.com/calling-and-using-the-color-picker-with-vba/

You can update **Example06.cs** file:

```csharp
private void buttonStartExample_Click(object sender, EventArgs e)
{
...
    case "xlDialogEditColor":
        returnValue = excelApplication.Dialogs[XlBuiltInDialog.xlDialogEditColor].Show(1);
        break;
...
}
```

**Comment by jozefizso** [comment]
Fixed the sample code.
