### ISSUE TITLE
Problem with Shim of NetOffice Addin (Unable to create Custom TaskPane)

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#199]
After using add Com Shim for the orginal addin name TestTaskPane (created by NetOffice Toolbox, without any change of code) (.Net 4.0, Net Office 1.7.4.1, Ribbon and Taskpane was used). The project run perfectly in dev computer (without Shim). But after using Shim, it has an error message when starting the addin as below (this error message will not show up if I remove the CustomPaneAttribute at the begining of Addin class). After close the message, the Addin ribbon tab still show up but Taskpane does not:
![image](https://user-images.githubusercontent.com/18644175/38801614-827669ce-4194-11e8-9fa3-1f886585bcce.png)

Error Content:

COMException;;Unable to create TestTaskPane.MyTaskPane(Excel CPU Usage).
System.Runtime.InteropServices.COMException (0x80004005): Unable to create TestTaskPane.MyTaskPane(Excel CPU Usage). ---> NetOffice.Exceptions.MethodCOMException (0x80004005): Failed to proceed Method on Office.ICTPFactory=>CreateCTP. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object argument1, Object argument2)
   at NetOffice.OfficeApi.Tools.CustomTaskPaneHandler.CreateCTP(Core factory, ICTPFactory taskPaneFactory, String fullName, String title, OnErrorHandler onError)

MethodCOMException;System.Object MethodReturn(NetOffice.ICOMObject, System.String, System.Object[]);Failed to proceed Method on Office.ICTPFactory=>CreateCTP.
NetOffice.Exceptions.MethodCOMException (0x80004005): Failed to proceed Method on Office.ICTPFactory=>CreateCTP. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object argument1, Object argument2)
   at NetOffice.OfficeApi.Tools.CustomTaskPaneHandler.CreateCTP(Core factory, ICTPFactory taskPaneFactory, String fullName, String title, OnErrorHandler onError)

TargetInvocationException;System.Object InvokeDispMethod(System.String, System.Reflection.BindingFlags, System.Object, System.Object[], Boolean[], Int32, System.String[]);Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)

COMException;;Unable to create specified ActiveX control.
System.Runtime.InteropServices.COMException (0x80004005): Unable to create specified ActiveX control.

**Comment by Linhin** [comment]
Thank you Jozef. I tested with the orginal code that create with NetOffice Developer Toolbox with CustomPaneAttribute as below: [CustomPane(typeof(MyTaskPane), "My TaskPane", true, PaneDockPosition.msoCTPDockPositionRight)]. And add Com Shim for the addin, load addin from Com shim and error still show up. (except Task pane, other components of add in still work)

However, when I run in debug mode for only Addin assembly, that work fine if my addin uses mscoree.dll to loaded in Excel. But if I add Com Shim to wrap the addin (not use mscoree.dll), It will show the error with creating custom task pane when Excel open.

**Comment by Linhin** [comment]
Finally found the problem. With com shim I have to set the the type of MyTaskPane ComVisible and then register  it.
