### ISSUE TITLE
Problems with Outlook Taskpane after Update to Outlook 2016 Build 1808

### ISSUE THREAD

**Issue by mrfloppy82** [NetOfficeFw/NetOffice#218]
Hello,

after Update to Build 1808 i can't create taskpanes anymore. Here is the .net Exception:

```
[2018-09-06 16:37:25,097] [1] ERROR Addin                [(null)] - NetOffice.Exceptions.MethodCOMException (0x80004005): Failed to proceed Method on Office.ICTPFactory=>CreateCTP. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object[] paramsArray)
   at NetOffice.OfficeApi.ICTPFactory.CreateCTP(String cTPAxID, String cTPTitle, Object cTPParentWindow)
```

The guys from addinexpress had simular Problems. The had a workaround.

https://www.add-in-express.com/forum/read.php?FID=5&TID=15105

But that does not work. Is this a NetOffice problem or a Microsoft problem? The UAC is disabled.

OS: Windows 10 1803 with August Updates.

Regards

Nico

**Comment by Charltsing** [comment]
I encountered a similar problem today, and after re-registering the plugin, the problem disappeared. I didn't find the cause of the problem. The guess may be related to the registration of usercontrol. I will continue to observe if there will be similar errors.

**Comment by jozefizso** [comment]
The `CreateCTP()` from NetOffice tries to create a COM object and as Charltsing says that object is not properly registered. Reregistering the object should help.
