### ISSUE TITLE
Getting "Factory is not initialized with NetOffice assemblies." exception

### ISSUE THREAD

**Issue by alemargo** [NetOfficeFw/NetOffice#278]
After upgrading to the latest version (1.7.4.11) of NetOffice.Core and NetOffice.Excel, the line of code below consistently fails
**Excel.Worksheet worksheet = _workBook.Worksheets.Add() as Excel.Worksheet;**

with the following error:
_NetOffice.NetOfficeException: Factory is not initialized with NetOffice assemblies.
   at NetOffice.Core.GetFactoryInfo(Object comProxy)
   at NetOffice.Core.CreateObjectFromComProxy(COMObject caller, Object comProxy)
   at NetOffice.ExcelApi.Sheets.Add()_

**Comment by alemargo** [comment]
Thank you. This did the trick!

**Comment by alemargo** [comment]
Works now!
