### ISSUE TITLE
Custom Task Pane does not work in MS Word

### ISSUE THREAD

**Issue by jozefizso** [NetOfficeFw/NetOffice#280]
I have written an AddIn using NetOfficeFw and it works great on my development machine but I am having trouble installing it on any other workstation. I have run RegAsm.exe on the .DLL and it reports "Types registered successfully" but when I launch Word it cannot create the custom task pane from my AddIn. Getting more insight with more descriptive error messages for what is behind this would definitely be helpful!

My AddIn is defined with the following attributes:

```csharp
[ComVisible(true)]
[COMAddin("AutoDocsToolbox", "AutoDocs Toolbox", LoadBehavior.LoadAtStartup)]
[ProgId("AutoDocsToolbox.Addin"), Guid("6F747690-3C89-4255-B191-82CDCFAE8813")]
[CustomUI("RibbonUI.xml", true)]
[CustomPane(typeof(AutoDocsToolboxPane), "AutoDocs Toolbox", true, PaneDockPosition.msoCTPDockPositionRight, PaneDockPositionRestrict.msoCTPDockPositionRestrictNone, 460, 800)]
public class Addin : Word.Tools.COMAddin
{
...
}
```

```
---------------------------
AutoDocs ToolBox
---------------------------
An error occurend in CTPFactoryAvailable
Unable to create NorseTechnologies.AutoDocs.Tools.AutoDocsToolboxPane(AutoDocs Toolbox).System.Runtime.InteropServices.COMException (0x80004005): Unable to create NorseTechnologies.AutoDocs.Tools.AutoDocsToolboxPane(AutoDocs Toolbox). ---> NetOffice.Exceptions.MethodCOMException (0x80004005): Failed to proceed Method on Office.ICTPFactory=>CreateCTP. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object argument1, Object argument2)
   at NetOffice.OfficeApi.Tools.CustomTaskPaneHandler.CreateCTP(Core factory, ICTPFactory taskPaneFactory, String fullName, String title, OnErrorHandler onError)NetOffice.Exceptions.MethodCOMException (0x80004005): Failed to proceed Method on Office.ICTPFactory=>CreateCTP. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteBaseReferenceMethodGet[T](Core value, ICOMObject caller, String name, Object argument1, Object argument2)
   at NetOffice.OfficeApi.Tools.CustomTaskPaneHandler.CreateCTP(Core factory, ICTPFactory taskPaneFactory, String fullName, String title, OnErrorHandler onError)System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Unable to create specified ActiveX control.
   --- End of inner exception stack trace ---
   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)System.Runtime.InteropServices.COMException (0x80004005): Unable to create specified ActiveX control.
---------------------------
OK   
---------------------------
```

_Originally posted by @chadknudson in https://github.com/NetOfficeFw/NetOffice/issues/271#issuecomment-664041885_

**Comment by jozefizso** [comment]
Hi @chadknudson,
is your custom task pane class `AutoDocsToolboxPane` exposed to COM as well?

`AutoDocsToolboxPane` must have `[ComVisible(true)]` and `Guid()]` attributes. You can define **ProgId**, but it must exactly match the full name of `AutoDocsToolboxPane` class (namespace + class name).

**Comment by chadknudson** [comment]
I have the AutoDocsToolboxPane decorated with the following attributes:

namespace NorseTechnologies.AutoDocs.Tools
{
    [ComVisible(true)]
    [Guid("68058A6B-705E-4E4D-A0E1-8943625B6FE8")]
    [ProgId("NorseTechnologies.AutoDocs.Tools.AutoDocsToolboxPane")]
    public partial class AutoDocsToolboxPane : UserControl, Word.Tools.ITaskPane
    {
...
    }
}

**Comment by jozefizso** [comment]
That looks good, both of your classes should be accessible from COM when defined this way.

One quick way to check is to use PowerShell:

```ps
New-Object -ComObject "NorseTechnologies.AutoDocs.Tools.AutoDocsToolboxPane"
```

This may reveal more details about why the class cannot be created from COM.

**Comment by chadknudson** [comment]
This is what the PowerShell script produced:

New-Object : Retrieving the COM class factory for component with CLSID {68058A6B-705E-4E4D-A0E1-8943625B6FE8} failed
due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
At line:1 char:1
+ New-Object -ComObject "NorseTechnologies.AutoDocs.Tools.AutoDocsToolb ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by chadknudson** [comment]
Is this possibly a 32-bit/64-bit issue? 

My project properties for the AddIn project platform target : x86. 

The systems to which I am attempting to deploy the AddIn are all running 64-bit Windows 10 Professional and Microsoft Word 2019 MSO (16.0.13001.20266) 32-bit.

My development system is Windows 10 Professional with Microsoft Word 2019 MSO (16.0.13001.20266) 32-bit as well.

**Comment by chadknudson** [comment]
Please close the issue and mark it an ID10T issue. I was missing a DLL in the setup program of my AddIn. I had added a dependency on a new Nuget package and forgot to add the corresponding .DLL to my setup application.

**Comment by jozefizso** [comment]
> Is this possibly a 32-bit/64-bit issue?

Yes, this is also common situation to look for - you should ensure you are calling right version of `regasm.exe` depending on which bitness you need to support.

32-bit regasm: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe`  
64-bit regasm: `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe`

By default, the 32-bit version of regasm is used by command line, so it will work for your 32-bit MS Office (even on 64-bit Windows)

**Comment by jozefizso** [comment]
@chadknudson No problem, this happens. I went this round countless times. I know how complicated this system is and what I should be looking for and yet I miss such details myself.
