### ISSUE TITLE
FactoryException: Class does not exist: NetOffice.OfficeApi.

### ISSUE THREAD

**Issue by jozefizso** [NetOfficeFw/NetOffice#289]
NetOffice library may report invalid class name in the `FactoryException` thrown from `CreateObjectFromComProxy()` method.

The `Class does not exist: NetOffice.OfficeApi.` should end with the class name of the component for which the instance could not be created and the `classType` is `null`.

https://github.com/NetOfficeFw/NetOffice/blob/f2e3dcdb670338fea874a4b832e2d26ff3f27ec5/Source/NetOffice/Core.cs#L1231

Invalid class name is created in the `GetFullComponentClassName()` method:
https://github.com/NetOfficeFw/NetOffice/blob/f2e3dcdb670338fea874a4b832e2d26ff3f27ec5/Source/NetOffice/ComTypes/TypeDescriptor.cs#L45

**Comment by jozefizso** [comment]
Stack trace:

```
NetOffice.Exceptions.FactoryException: Class does not exist: NetOffice.OfficeApi.
  Module "NetOffice.Core", in CreateObjectFromComProxy
  Module "NetOffice.Core", in CreateObjectFromComProxy
  Module "NetOffice.Utils", in GetProxyEnumeratorAsProperty
  Module "NetOffice.OfficeApi.DocumentProperties", in GetEnumerator
  Module "System.Linq.Enumerable", in First
```

**Comment by Offbeatmammal** [comment]
intermittently seeing the same issue, curious if there are any suggested workarounds or planned fix?

    NetOffice.Exceptions.FactoryException
      HResult=0x80131500
      Message=Class does not exist: NetOffice.PowerPointApi.
      Source=NetOffice
      StackTrace:
       at NetOffice.Core.CreateObjectFromComProxy(IFactoryInfo factoryInfo, ICOMObject caller, Object comProxy, Type 
    comProxyType, String className, String fullClassName, Boolean allowDynamicObject)
       at NetOffice.Core.CreateObjectFromComProxy(ICOMObject caller, Object comProxy, Boolean allowDynamicObject)
       at NetOffice.Utils.<GetProxyEnumeratorAsProperty>d__13.MoveNext()
       at NetOffice.PowerPointApi.Shapes.<GetEnumerator>d__121.MoveNext()

**Comment by IainDM** [comment]
Also seeing this intermittently. StackTrace below from an enumeration over a sheet's CustomProperties

NetOffice.Exceptions.FactoryException: Class does not exist: NetOffice.ExcelApi.
at NetOffice.Core.CreateObjectFromComProxy(NetOffice.IFactoryInfo factoryInfo, NetOffice.ICOMObject caller, System.Object comProxy, System.Type comProxyType, System.String className, System.String fullClassName, System.Boolean allowDynamicObject) at offset 348
at NetOffice.Core.CreateObjectFromComProxy(NetOffice.ICOMObject caller, System.Object comProxy, System.Boolean allowDynamicObject) at offset 227
at NetOffice.Utils.<GetProxyEnumeratorAsProperty>d__13.MoveNext() at offset 353
at NetOffice.ExcelApi.CustomProperties.<GetEnumerator>d__26.MoveNext() at offset 101

**Comment by jonathandlo** [comment]
I am getting this as well, in case my issue is related:

`foreach (var footer in lastSection.Footers)`

```
Exception has occurred: CLR/NetOffice.Exceptions.FactoryException
An unhandled exception of type 'NetOffice.Exceptions.FactoryException' occurred in NetOffice.dll: 'Class does not exist: NetOffice.WordApi.System.__ComObject'
   at NetOffice.Core.CreateObjectFromComProxy(IFactoryInfo factoryInfo, ICOMObject caller, Object comProxy, Type comProxyType, String className, String fullClassName, Boolean allowDynamicObject)
   at NetOffice.Core.CreateObjectFromComProxy(ICOMObject caller, Object comProxy, Boolean allowDynamicObject)
   at NetOffice.Utils.<GetProxyEnumeratorAsProperty>d__13.MoveNext()
   at NetOffice.WordApi.HeadersFooters.<GetEnumerator>d__25.MoveNext()
```

I can partially get around this by skipping the enumerator and accessing the child item directly. Using the latest 2.0.0 preview 20, .net 8 project.
