### ISSUE TITLE
set_Value with xlRangeValueXMLSpreadsheet

### ISSUE THREAD

**Issue by slawek-pelka-3301** [NetOfficeFw/NetOffice#310]
Hi!
I am new here, I stumbled upon the netoffice library and I am amazed by what it offers, it perfectly suits my need.
However.
I encounter the roadblock when I try to my old Microsoft.Interop code to netoffice.
Example code below throws exception:
```
var xml = activeSheet.get_Range("A1", Type.Missing).get_Value(rangeValueDataType: XlRangeValueDataType.xlRangeValueXMLSpreadsheet);
activeSheet.get_Range("B1", Type.Missing).set_Value(rangeValueDataType: XlRangeValueDataType.xlRangeValueXMLSpreadsheet, xml);
```

The exception is as follows:

```
> NetOffice.Exceptions.PropertySetCOMException
>   HResult=0x80004005
>   Message=Failed to proceed PropertySet on Excel.Range=>Value.
>   Source=NetOffice
>   StackTrace:
>    at NetOffice.Invoker.PropertySet(ICOMObject comObject, String name, Object[] value)
>    at NetOffice.CorePropertySetExtensions.ExecutePropertySet(Core value, ICOMObject caller, String name, Object newValue, Object argument)
>    at NetOffice.ExcelApi.Range_.set_Value(Object rangeValueDataType, Object value)
>    at AddInForConnect.ExcelController.DownloadTest(Int32 number) in C:\Repos\excel_addin_for_connect\AddIn\AddInForConnect\ExcelController.cs:line 111
>    at AddInForConnect.ExcelController.ShowWizard() in C:\Repos\excel_addin_for_connect\AddIn\AddInForConnect\ExcelController.cs:line 46
>    at AddInForConnect.CustomRibbon.OnShowWizard(IRibbonControl control) in C:\Repos\excel_addin_for_connect\AddIn\AddInForConnect\CustomRibbon.cs:line 79

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
COMException: Type mismatch. (Exception from HRESULT: 0x80020005 (**DISP_E_TYPEMISMATCH**))
```
This roadblock is on my critical path, please give me a hope I don't have to return to Microsoft.Interop ;-)

If anybody asks why I am using this technique: XmlSpreadsheet is very efficient way of putting large amount of data to live excel spreadsheet. This minimizes number of calls to interop especially if you want add formatting (and I use e.g. setting colors of text etc).

**Comment by jozefizso** [comment]
Hi, do you have sample project which reproduces the issue?

**Comment by slawek-pelka-3301** [comment]
It's highly repeatable. Below I modified standard netoffice sample 01, by removing creating shapes (not necessary for reproduce the issue) and added two lines to copy cell A1 to B1, using xmlSpreadsheet method:

        public void RunExample()
        {
            // start excel and turn off msg boxes
            Excel.Application excelApplication = new Excel.Application();
            excelApplication.DisplayAlerts = false;

            // create a utils instance, no need for but helpful to keep the lines of code low
            CommonUtils utils = new CommonUtils(excelApplication);

            // add a new workbook
            Excel.Workbook workBook = excelApplication.Workbooks.Add();
            Excel.Worksheet workSheet = (Excel.Worksheet)workBook.Worksheets[1];

            workSheet.Cells[1, 1].Value = "We have 2 simple shapes created.";

>             var xml = workSheet.Cells[1, 1].get_Value(rangeValueDataType: XlRangeValueDataType.xlRangeValueXMLSpreadsheet);
>             workSheet.Cells[1, 2].set_Value(rangeValueDataType: XlRangeValueDataType.xlRangeValueXMLSpreadsheet, xml);
> 

            // save the book - utils want build the filename for us
            string workbookFile = utils.File.Combine(HostApplication.RootDirectory, "Example01", DocumentFormat.Normal);
            workBook.SaveAs(workbookFile);

            // close excel and dispose reference
            excelApplication.Quit();
            excelApplication.Dispose();

            // show end dialog
            HostApplication.ShowFinishDialog(null, workbookFile);
        }

**Comment by slawek-pelka-3301** [comment]
Let me know if I can help further,
Best Regards!

**Comment by JD-Robbs** [comment]
Same here - calling set_Value throws the same Exception.

Unfortunately, only downgrading to 1.7.3 fixed it for me.

**Comment by slawek-pelka-3301** [comment]
Thank You JD_Robbs for sharing the info.
Could be helpful when I will get back to this project, will consider downgrading.
On the other hand, I am curious what has changed to introduce the issue.
Unfortunately I have not enough time atm to compare branches :)
